=== katsiaryna-silina/medicines/src/main/resources/medicines.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:mdc="http://www.example.com/medicines"
            targetNamespace="http://www.example.com/medicines"
            elementFormDefault="qualified">
    <xsd:element name="medicines">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="medicine" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="company" type="xsd:string"/>
                            <xsd:element name="group" type="xsd:string"/>
                            <xsd:element name="versions">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="version" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="medicineType">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:enumeration value="effervescent tablets"/>
                                                                <xsd:enumeration value="capsules"/>
                                                                <xsd:enumeration value="tablets"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                    <xsd:element name="packages">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="package" maxOccurs="unbounded">
                                                                    <xsd:complexType>
                                                                        <xsd:sequence>
                                                                            <xsd:element name="packageType">
                                                                                <xsd:simpleType>
                                                                                    <xsd:restriction base="xsd:string">
                                                                                        <xsd:enumeration value="tube"/>
                                                                                        <xsd:enumeration
                                                                                                value="bottle"/>
                                                                                        <xsd:enumeration value="jar"/>
                                                                                        <xsd:enumeration value="pack"/>
                                                                                    </xsd:restriction>
                                                                                </xsd:simpleType>
                                                                            </xsd:element>
                                                                            <xsd:element name="number">
                                                                                <xsd:simpleType>
                                                                                    <xsd:restriction
                                                                                            base="xsd:positiveInteger">
                                                                                        <xsd:maxInclusive value="1000"/>
                                                                                    </xsd:restriction>
                                                                                </xsd:simpleType>
                                                                            </xsd:element>
                                                                            <xsd:element name="price">
                                                                                <xsd:simpleType>
                                                                                    <xsd:restriction base="xsd:decimal">
                                                                                        <xsd:fractionDigits value="2"/>
                                                                                        <xsd:minInclusive value="0.01"/>
                                                                                    </xsd:restriction>
                                                                                </xsd:simpleType>
                                                                            </xsd:element>
                                                                        </xsd:sequence>
                                                                        <xsd:attribute name="isSealed"
                                                                                       type="xsd:boolean"
                                                                                       default="false"
                                                                                       use="optional"/>
                                                                    </xsd:complexType>
                                                                </xsd:element>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="dosage">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:minLength value="3"/>
                                                                <xsd:maxLength value="15"/>
                                                                <xsd:pattern value="[0-9]* [a-zA-Z]*"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                    <xsd:element name="certificate">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="certificateName"
                                                                             type="mdc:limitedText"/>
                                                                <xsd:element name="whoIssued" type="mdc:limitedText"/>
                                                                <xsd:element name="registrationNumber"
                                                                             type="mdc:limitedText"/>
                                                                <xsd:element name="registrationDateFrom"
                                                                             type="xsd:date"/>
                                                                <xsd:element name="registrationDateTo"
                                                                             type="xsd:date"/>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" use="required" type="xsd:ID"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="limitedText">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="3"/>
            <xsd:maxLength value="50"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== katsiaryna-silina/medicines/src/main/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<mdc:medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:mdc="http://www.example.com/medicines"
               xsi:schemaLocation="http://www.example.com/medicines medicines.xsd">
    <mdc:medicine id="a23e4567-e89b-12d3-a456-426614174000">
        <mdc:name>Upsarin Upsa</mdc:name>
        <mdc:company>UPSA, SAS.</mdc:company>
        <mdc:group>NSAID</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>effervescent tablets</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>16</mdc:number>
                    <mdc:price>19.60</mdc:price>
                </mdc:package>
                <mdc:dosage>500 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>6664/04/07/09/12/14/17/19</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2019-08-02</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2024-08-02</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
            <mdc:version>
                <mdc:medicineType>effervescent tablets</mdc:medicineType>
                <mdc:package isSealed="true">
                    <mdc:packageType>tube</mdc:packageType>
                    <mdc:number>10</mdc:number>
                    <mdc:price>8.02</mdc:price>
                </mdc:package>
                <mdc:dosage>500 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>1610/96/01/06/10/12/16/19</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2016-06-06</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2026-06-06</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
    <mdc:medicine id="s234ds67-e89b-12d3-a456-426614174000">
        <mdc:name>Aspirin-C</mdc:name>
        <mdc:company>BAYER BITTERFELD, GmbH</mdc:company>
        <mdc:group>NSAID</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>effervescent tablets</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>10</mdc:number>
                    <mdc:price>9.00</mdc:price>
                </mdc:package>
                <mdc:dosage>400 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>2459/96/02/07/12/17</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2017-10-30</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2022-10-30</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
    <mdc:medicine id="aq3e4567-e89b-12d3-a456-426614174820">
        <mdc:name>Alka-Seltze</mdc:name>
        <mdc:company>BAYER BITTERFELD, GmbH</mdc:company>
        <mdc:group>NSAID</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>effervescent tablets</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>10</mdc:number>
                    <mdc:price>11.22</mdc:price>
                </mdc:package>
                <mdc:dosage>324 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>454/94/04/07/09/14/19</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2017-10-31</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2022-10-31</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
    <mdc:medicine id="q234ty67-g39s-12d3-a456-426614174111">
        <mdc:name>Cardiomagnyl</mdc:name>
        <mdc:company>TAKEDA, GmbH</mdc:company>
        <mdc:group>NSAID</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>tablets</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>jar</mdc:packageType>
                    <mdc:number>100</mdc:number>
                    <mdc:price>18.03</mdc:price>
                </mdc:package>
                <mdc:dosage>75 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>452/02/09/01/24/11</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2019-12-21</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2024-12-21</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
    <mdc:medicine id="u234ty77-g29q-12w3-a354-4s6f14674222">
        <mdc:name>Omez</mdc:name>
        <mdc:company>Dr. Reddy's Laboratories, LTD</mdc:company>
        <mdc:group>proton pump inhibitor</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>capsules</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>30</mdc:number>
                    <mdc:price>34.06</mdc:price>
                </mdc:package>
                <mdc:dosage>20 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>1136/95/01/06/11/17</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2017-01-13</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2023-01-13</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
            <mdc:version>
                <mdc:medicineType>capsules</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>30</mdc:number>
                    <mdc:price>23.82</mdc:price>
                </mdc:package>
                <mdc:dosage>10 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>8956/09/10/10/11/14/17/19/21/21</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2019-08-29</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2024-08-29</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
            <mdc:version>
                <mdc:medicineType>capsules</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>30</mdc:number>
                    <mdc:price>49.50</mdc:price>
                </mdc:package>
                <mdc:dosage>40 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>9346/02/10/10/11/14/17/20/22/22</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2020-04-12</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2025-04-12</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
    <mdc:medicine id="q114ty67-g39s-12de-a456-42as14174111">
        <mdc:name>Omeprez</mdc:name>
        <mdc:company>S.C. Rompharm Company S.R.L.</mdc:company>
        <mdc:group>proton pump inhibitor</mdc:group>
        <mdc:versions>
            <mdc:version>
                <mdc:medicineType>capsules</mdc:medicineType>
                <mdc:package>
                    <mdc:packageType>pack</mdc:packageType>
                    <mdc:number>30</mdc:number>
                    <mdc:price>34.32</mdc:price>
                </mdc:package>
                <mdc:dosage>20 mg</mdc:dosage>
                <mdc:certificate>
                    <mdc:name>Registration certificate</mdc:name>
                    <mdc:whoIssued>Ministry of Health of the Republic of Belarus</mdc:whoIssued>
                    <mdc:registrationNumber>6217/03/07/08/13/18</mdc:registrationNumber>
                    <mdc:registrationDateFrom>2018-12-03</mdc:registrationDateFrom>
                    <mdc:registrationDateTo>2023-12-03</mdc:registrationDateTo>
                </mdc:certificate>
            </mdc:version>
        </mdc:versions>
    </mdc:medicine>
</mdc:medicines>
